# -----------------------------------------------------
# Colors (Industrial One-Source-of-Truth)
# -----------------------------------------------------

# Hlavné farby
$background = rgb(02000D)           # night_sky
$foreground = rgb(7C091B)           # pure red
$selection_background = rgb(4d0000)
$selection_foreground = rgb(DBD3C0) # cream
$semi_transparent = rgba(0, 0, 0, 0.5)

# Špeciálne pre Kitty / Kurzor
$cursor = rgb(B31C20)               # bright_red
$cursor_text_color = rgb(000000)
$url_color = rgb(ff4545)            # neon_red

# ANSI 16 farieb terminálu
# Čierna
$color0 = rgb(02000D)               # black
$color8 = rgb(110F1D)               # heavy_black

# Červená
$color1 = rgb(4D0000)               # red
$color3 = rgb(B31C20)               # bright_red

# Zelená (nahradená tvojou tmavočervenou)
$color10 = rgb(1a0505)               # dark_red
$color9 = rgb(ff4545)              # neon_red

# Žltá (nahradená tvojou jemnou červenou)
$color2 = rgb(601C31)               # soft_red
$color11 = rgb(800000)   #800000    # border_red

# Modrá (tvoja tmavá modrá/čierna)
$color6 = rgb(70162F)               # candy_red
$color14 = rgb(171731)    #171731    # brick_blue

# Magenta
$color13 = rgb(34343D)               # steel
$color5 = rgb(7C091B)              # pure red

# Cyan
$color4 = rgb(877D74)               # rock
$color12 = rgb(ABA9B1)              # gravel

# Biela
$color7 = rgb(DBD3C0)               # cream
$color15 = rgb(FFFFFF)              # bright_white

# -----------------------------------------------------
