# -----------------------------------------------------
# Hyprlock
# -----------------------------------------------------

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = /home/arxibald_00/Desktop/HyprlandAssets/upscaled_gibbli_train.jpeg
  blur_passes = 2
}

# TIME
label {
  monitor =
  text = $TIME
  color = rgb(120, 0, 0)
  font_size = 90
  font_family = JetBrains Mono
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = rgb(200, 200, 200)
  font_size = 25
  font_family = JetBrains Mono
  position = -30, -150
  halign = right
  valign = top
}

# INPUT FIELD
input-field {
  monitor =
  size = 240, 40
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = rgb(200, 0, 0)
  inner_color = rgb(30, 0, 0)
  font_color = rgb(255, 255, 255)
  fade_on_empty = false
  placeholder_text = <i>Logged in as <b>$USER</b></i>
  rounding = 3
  hide_input = false
  check_color = rgb(255, 255, 255)
  fail_color = rgb(255, 0, 0)
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = rgb(255, 255, 255)
  position = 0, -50
  halign = center
  valign = center
}


# -----------------------------------------------------
