# -----------------------------------------------------
# Hypridle
# -----------------------------------------------------

general {
    lock_cmd = pidof hyprlock || hyprlock       # toto povie systému, čo má použiť na zamknutie
    before_sleep_cmd = loginctl lock-session    # zamkne pred uspaním ntb
    after_sleep_cmd = hyprctl dispatch dpms on  # zapne displej po prebudení
}

# 5min lock
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}


# -----------------------------------------------------
