# -----------------------------------------------------
# Hyprpaper
# -----------------------------------------------------

preload = /home/arxibald_00/Desktop/HyprlandAssets/upscaled_gibbli_train.jpeg
wallpaper = ,/home/arxibald_00/Desktop/HyprlandAssets/upscaled_gibbli_train.jpeg


# -----------------------------------------------------
