# -----------------------------------------------------
# Animations
# -----------------------------------------------------

animations {
  enabled = yes

# Default curves
#        NAME,           X0,   Y0,   X1,   Y1
# bezier = easeOutQuint,   0.23, 1,    0.32, 1
# bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
# bezier = almostLinear,   0.5,  0.5,  0.75, 1
# bezier = quick,          0.15, 0,    0.1,  1
    bezier = sharp,          0.05, 0.9,  0.1,  1

    # Default animations
    #           NAME,          ONOFF, SPEED, CURVE, [STYLE]
    animation = global,        1,     10,    sharp,
    animation = border,        1,     5.39,  sharp,
    animation = windows,       1,     4.79,  sharp,
    animation = windowsIn,     1,     4.1,   sharp, popin 87%
    animation = windowsOut,    1,     1.49,  sharp, popin 87%
    animation = fadeIn,        1,     1.73,  sharp,
    animation = fadeOut,       1,     1.46,  sharp,
    animation = fade,          1,     3.03,  sharp,
    animation = layers,        1,     3.81,  sharp,
    animation = layersIn,      1,     4,     sharp, fade
    animation = layersOut,     1,     1.5,   sharp, fade
    animation = fadeLayersIn,  1,     1.79,  sharp,
    animation = fadeLayersOut, 1,     1.39,  sharp,
    animation = workspaces,    1,     1.94,  sharp, fade
    animation = workspacesIn,  1,     1.21,  sharp, fade
    animation = workspacesOut, 1,     1.94,  sharp, fade
    animation = zoomFactor,    1,     7,     sharp,
}


# -----------------------------------------------------
