# -----------------------------------------------------
# Tiling
# -----------------------------------------------------

dwindle {
    # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    pseudotile = true
    # You probably want this
    preserve_split = true
}

master {
    new_status = master
}


# -----------------------------------------------------
