# -----------------------------------------------------
# MISC
# -----------------------------------------------------

misc {

    allow_session_lock_restore = true
    
    # disables pussies
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    
    # variable frame rate
    vfr = true

    # wake up
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true

    # free ram
    close_special_on_empty = true

    # swallowing
    enable_swallow = true
    swallow_regex = ^(kitty)$
}


# -----------------------------------------------------
