# -----------------------------------------------------
# Monitor
# -----------------------------------------------------

#monitor name,resolution & refresh rate,starting point,scale
monitor= eDP-1,preferred,0x0,1


# -----------------------------------------------------
