# -----------------------------------------------------
# Window
# -----------------------------------------------------

general {
  gaps_in = 5
    gaps_out = 10

    border_size = 0

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

# Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

# Tearing - keep off
    allow_tearing = false
    layout = dwindle
}


# -----------------------------------------------------
# Dwindle Layout (Špirálové ukladanie)
# -----------------------------------------------------

dwindle {
  pseudotile = true 
    preserve_split = true 
# Nové okno sa otvorí v smere, kde máš kurzor
    force_split = 2
}


# -----------------------------------------------------
# Master Layout (Jedno hlavné veľké okno, ostatné v stĺpci)
# -----------------------------------------------------

master {
  new_status = master
}


# -----------------------------------------------------
