# -----------------------------------------------------
# Windowrule
# -----------------------------------------------------

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#Improve stability through not allowing minimized windows to read input
#render {
#    explicit_sync = true
#}
# Cava - pokus
# windowrulev2 = tile, class:^($cavaClass)$
# windowrulev2 = pseudotile, class:^($cavaClass)$
# windowrulev2 = size 800 400, class:^($cavaClass)$


# -----------------------------------------------------
